# Generated by Django 4.0.6 on 2022-08-31 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gsk', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viewer',
            name='user',
        ),
        migrations.DeleteModel(
            name='Views',
        ),
        migrations.DeleteModel(
            name='Viewer',
        ),
    ]
