# Generated by Django 4.0.6 on 2022-08-31 06:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gsk', '0002_remove_viewer_user_delete_views_delete_viewer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Views',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth', models.IntegerField(default=0)),
                ('noauth', models.IntegerField(default=0)),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='дата')),
                ('ip', models.GenericIPAddressField(default=0)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
