# Generated by Django 4.0.6 on 2022-08-31 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gsk', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Views',
        ),
    ]
