# Generated by Django 4.0.6 on 2022-07-13 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='file/%Y/%m/%d/', verbose_name='Файл'),
        ),
    ]
