# Generated by Django 4.0.6 on 2022-07-13 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_post_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='photo',
        ),
    ]
