# Generated by Django 4.0.6 on 2022-09-05 08:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0004_post_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Now',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='название срочно')),
                ('body', models.TextField(verbose_name='текст срочно')),
                ('create', models.DateTimeField(auto_now_add=True, null=True, verbose_name='создан')),
                ('date', models.DateField(verbose_name='окончание')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='now_post', to='news.post', verbose_name='slug')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='now_user', to=settings.AUTH_USER_MODEL, verbose_name='автор')),
            ],
        ),
    ]
