# Generated by Django 4.0.6 on 2022-09-07 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_now'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='now',
            options={'verbose_name': 'срочно', 'verbose_name_plural': 'Срочно'},
        ),
    ]
