# Generated by Django 4.0.6 on 2022-07-13 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='изменен'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='date',
            field=models.DateTimeField(verbose_name='изменен'),
        ),
    ]
