# Generated by Django 4.0.6 on 2022-07-13 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_alter_post_date_alter_topic_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='date',
            field=models.DateTimeField(auto_now=True, verbose_name='изменен'),
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(auto_now=True, verbose_name='изменен'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='date',
            field=models.DateTimeField(auto_now=True, verbose_name='изменен'),
        ),
    ]
