# Generated by Django 4.0.6 on 2022-07-13 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_alter_forum_date_alter_post_date_alter_topic_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='file/%Y/%m/%d/', verbose_name='Файл'),
        ),
    ]
