# Generated by Django 4.0.6 on 2022-09-08 14:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0004_delete_reg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forum',
            old_name='date_create',
            new_name='create',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='date_create',
            new_name='create',
        ),
        migrations.RenameField(
            model_name='topic',
            old_name='date_create',
            new_name='create',
        ),
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='body',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='user',
        ),
        migrations.AddField(
            model_name='forum',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='forum',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='file/%Y/%m/%d/', verbose_name='Файл'),
        ),
        migrations.AddField(
            model_name='forum',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='img/%Y/%m/%d/', verbose_name='img'),
        ),
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='file/%Y/%m/%d/', verbose_name='Файл'),
        ),
        migrations.AddField(
            model_name='post',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='img/%Y/%m/%d/', verbose_name='img'),
        ),
        migrations.AddField(
            model_name='topic',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='topic',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='img/%Y/%m/%d/', verbose_name='img'),
        ),
        migrations.AlterField(
            model_name='forum',
            name='desc',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание форума'),
        ),
        migrations.AlterField(
            model_name='forum',
            name='forum',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Форум'),
        ),
        migrations.AlterField(
            model_name='post',
            name='desc',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='post',
            name='forum',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='forum.forum'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='post',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='forum.topic'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='desc',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание темы'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='forum',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='forum.forum'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='topic',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Тема'),
        ),
    ]
