# Generated by Django 4.0.6 on 2022-09-07 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top', models.CharField(max_length=150, verbose_name='Топ')),
                ('phone', models.CharField(max_length=64, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254)),
                ('map1', models.TextField(verbose_name='Карта1')),
                ('gover', models.TextField(verbose_name='Правление')),
                ('audit', models.TextField(verbose_name='Ревизия')),
                ('finance', models.TextField(verbose_name='Ревизия')),
                ('news', models.TextField(verbose_name='Ревизия')),
                ('power', models.TextField(verbose_name='Ревизия')),
                ('body', models.TextField(verbose_name='текст новости')),
                ('map2', models.TextField(verbose_name='Карта2')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото')),
                ('file', models.FileField(blank=True, null=True, upload_to='file/%Y/%m/%d/', verbose_name='Файл')),
                ('date', models.DateField(verbose_name='изменен')),
            ],
            options={
                'verbose_name': 'контакт',
            },
        ),
    ]
