# Generated by Django 4.0.6 on 2022-09-08 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'контакт', 'verbose_name_plural': 'контакты'},
        ),
        migrations.AlterField(
            model_name='contact',
            name='audit',
            field=models.TextField(blank=True, null=True, verbose_name='Ревизия'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='body',
            field=models.TextField(blank=True, null=True, verbose_name='текст новости'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='finance',
            field=models.TextField(blank=True, null=True, verbose_name='Финансы'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='gover',
            field=models.TextField(blank=True, null=True, verbose_name='Правление'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='news',
            field=models.TextField(blank=True, null=True, verbose_name='Новости'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='power',
            field=models.TextField(blank=True, null=True, verbose_name='Свет'),
        ),
    ]
