# Generated by Django 4.0.6 on 2022-07-13 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line', models.CharField(max_length=16)),
                ('date', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Ряд',
                'verbose_name_plural': 'Ряды',
            },
        ),
        migrations.CreateModel(
            name='CountLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.FloatField(default=0, verbose_name='счетчик')),
                ('date', models.DateField(verbose_name='дата')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='power.line', verbose_name='ряд')),
            ],
            options={
                'verbose_name': 'Счет ряда',
                'verbose_name_plural': 'Счет рядов',
            },
        ),
        migrations.CreateModel(
            name='CountBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box', models.CharField(max_length=16)),
                ('count', models.FloatField(default=0)),
                ('date', models.DateField()),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='power.line')),
            ],
            options={
                'verbose_name': 'Счет бокса',
                'verbose_name_plural': 'Счет боксов',
            },
        ),
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box', models.CharField(max_length=16)),
                ('date', models.DateTimeField(auto_now=True, null=True)),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='power.line')),
            ],
            options={
                'verbose_name': 'Бокс',
                'verbose_name_plural': 'Боксы',
            },
        ),
    ]
